### ISSUE TITLE
HCN Support

### ISSUE THREAD

**Issue by Dolphinssss** [zardoru/raindrop#36]
HELL CHARGE NOTE Support as per charatbeatHDX VIOLET v1.10 implementation.
http://hitkey.nekokan.dyndns.info/diary1602.php#D160217

HCNs are are a new type of Charge Notes (Long Notes) added in beatmania IIDX 23 copula.
The game will gradually deplete your gauge every 8th for as long as the duration of the HCN if you miss it. 
Unlike regular CNs, it can be reactivated if you miss it, making your health regain again.

In BMS file, `#OPTION` can be used. 
charatbeatHDX VIOLET v1.10 uses this format:

`#OPTION charatbeatHDX:LONGMODE n`
The variable **n** can be either **0** or **1**

> # OPTION charatbeatHDX:LONGMODE 0
> 
> for regular charge notes

or

> # OPTION charatbeatHDX:LONGMODE 1 (HCN mode)
> 
> for HELL CHARGE NOTES.

**Comment by zardoru** [comment]
We are not trying to emulate IIDX mechanics. In addition, I have asked bits of the english side of the VSRG community and they've shared the conclusion that HCNs are not particularily hard at the LN end-game level.

That is, HCNs are only hard for people that are unable to keep a note held at the same time that other notes are going on. As such this is very much IIDX specific.

Closing because of a lack of interest.
